Preserve last used units in the Journal activity
sugarlabs/convert pull request #32
Opened 2019-08-05 04:27 UTC by nswarup14

Fixes #13 

Kindly review

2019-08-06 10:37 UTC, chimosky requested changes

2019-08-06 10:37 UTC, chimosky commented on activity.py
> +        if 'state' in self.metadata:
L245-L249 should be in `read_file`.

2019-08-06 10:48 UTC, chimosky commented
Tested, comments.

The units aren't preserved, the `combobox` items show the last units accessed but both units show the first item in the `combobox` and the convert values aren't shown - the value being converted and the output of the conversion -.

2019-08-06 11:05 UTC, chimosky commented on activity.py
> +        self._active_unit = unit_type
Is there a use for this?.

2019-08-06 11:05 UTC, chimosky commented on activity.py
> +            print('i entered')
Could this be more informative, probably use `logging` instead of `print`.

2019-08-06 11:27 UTC, nswarup14 commented on activity.py
> +        self._active_unit = unit_type
@chimosky
This is to keep track of what type of units are currently being used.
If the user changes from `length` to ``

2019-08-06 11:28 UTC, nswarup14 commented on activity.py
> +            print('i entered')
Sorry
That was actually a debug message. I shall remove it.

2019-08-07 07:37 UTC, quozl commented
Tested f988ce5.

* [ ] the unit type (dimension) is not restored on resume,
* [ ] the unit is saved as a number not a name, which means any changes to units in the program may cause journal objects to silently corrupt when the activity is upgraded.

The first point is an obvious functional failure which you should have seen in testing.  Please test before commit, or if the work is not finished mark the pull request as draft, thanks.

2019-08-12 07:50 UTC, quozl commented
I'm working on rebasing this.  Should finish tomorrow.

2019-08-12 09:00 UTC, quozl commented
@chimosky, @nswarup14, please test 5c1dbd3.  Yet to finish rebase, but it is in a working state for me.

2019-08-12 10:31 UTC, nswarup14 commented
@quozl @chimosky 
Tested https://github.com/sugarlabs/convert/commit/5c1dbd3f99190ceaeea92df0c58bc2f0e0e6e974 on Sugar v0.114, Ubuntu 18.04.

Individual units for both the combo boxes are being preserved.  The dimension is being preserved as well.
However, the RadioToolButton at the toolbar is not updated, on activity resume.

For example, if I save the activity with `Area` as dimension, on activity resume, the `length` RadioToolButton is set active.

I will try to fix this.

Thanks!

2019-08-12 10:55 UTC, nswarup14 commented
@quozl @chimosky 
As mentioned in the earlier comment, I have fixed the problem of RadioToolButton not updating with the preserved dimension.

Kindly review.

Thanks

2019-08-12 12:44 UTC, quozl commented
Thanks.  Reworked.  Please test 4c232d5.  I'll plan to rebase tomorrow my time.

2019-08-12 12:59 UTC, nswarup14 commented
@quozl 
Tested https://github.com/sugarlabs/convert/commit/4c232d5c0b67a136dc81491db1ddb8e39e063a23
on Sugar v0.114
Works as expected. Logs contain no errors.

2019-08-13 01:01 UTC, quozl commented
Rebased as 5ad6553.

@Aniket21mathur, I've checked and none of the code you wrote in https://github.com/sugarlabs/convert/pull/23/files seems to have been used.  Let me know if you think it has, and I'll adjust the _Co-authored-by_ tag.

I thought it was all finished, but no.  Yet to be done;

* [ ] a button to reset dimension and units to default, per https://github.com/sugarlabs/convert/issues/13, unless we can agree it isn't needed,
* [ ] discuss whether it makes sense to save the _from value_ and _to value_ in the journal object.

2019-08-13 07:24 UTC, nswarup14 commented
@quozl @chimosky 

> a button to reset dimension and units to default, per #13, unless we can agree it isn't needed,

I feel we can add a button which says reset to SI unit for each corresponding dimension.

> discuss whether it makes sense to save the from value and to value in the journal object.

Yes it does. If we are saving the last used units and dimensions, the next step would be to save the last converted values. If a user wishes to pick up from where he left, then the feature would be ideal.

2019-08-14 00:02 UTC, chimosky commented
Tested 5ad6553.

Works as expected. 

> - [ ] discuss whether it makes sense to save the from value and to value in the journal object.

I think it makes sense to save the from value and to value in the journal object.

2019-08-14 02:14 UTC, quozl commented
>     * [ ]  a button to reset dimension and units to default, per #13, unless we can agree it isn't needed,

My vote is no.  As of 5ad65539e4eb6f2391d72481d1850bbc0c1464ec each time a dimension radio tool button is pressed, the unit is already reset to default for that dimension.  Every button is a reset.  Also, per https://github.com/sugarlabs/convert/issues/33 there is no room left on the toolbar.  What do you think?

>     * [ ]  discuss whether it makes sense to save the _from value_ and _to value_ in the journal object.

My vote is yes for this one.  In ad63d02.  Please test.

Fixes #24.

2019-08-14 04:51 UTC, nswarup14 commented
@quozl @chimosky 
Tested and reviewed https://github.com/sugarlabs/convert/commit/ad63d02e5f8f39b3eab86d7e83ff3d56f8a2a26d.

The activity stores the _from_value_ and _to_value_ correctly.

2019-08-16 05:49 UTC, merged